IcMimarlikProje/Areas/admin/Controllers/AdminController.cs
using IcMimarlikProje.Areas.admin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace IcMimarlikProje.Areas.admin.Controllers
{
   
    public class AdminController : Controller
    {
        [AuthorizeAdminUserAttribute]
        public ActionResult AdminSayfasi()
        {
            return View();
        }
        public ActionResult Giris()
        {
            if (Session["AdminUser"]!=null)
            {
                return RedirectToAction(nameof(AdminSayfasi));
            }
            else
                return View();
        }
        [HttpPost]
        public ActionResult Giris( Kullanici kullanici)
        {
            //These values are not used in the real site for security purposes.
            if (kullanici.KullaniciSifresi.Equals("ad") && kullanici.KullaniciSifresi.Equals("sifre"))
            {

                Session["AdminUser"] = "1";
                return RedirectToAction(nameof(AdminSayfasi));
            }
            else
            {
                return RedirectToAction(nameof(Giris));
            }
        }
        public ActionResult Logout()
        {
            Session["AdminUser"] = null;
            return RedirectToAction(nameof(Giris));
        }
    }
}

IcMimarlikProje/Areas/admin/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IcMimarlikProje.Areas.admin.Models;
using IcMimarlikProje.Models.Data;

namespace IcMimarlikProje.Controllers
{
    [AuthorizeAdminUserAttribute]
    public class ArticlesController : Controller
    {
        private SeraKaraalpContext db = new SeraKaraalpContext();

        // GET: Articles
        public ActionResult Index()
        {
            if (Session["AdminUser"].ToString() == "1")
            {              
                var articles = db.Articles.ToList();
                return View(articles.ToList());
            }
            else
                return RedirectToAction("Giris", "Admin");

        }

        // GET: Articles/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        
        public ActionResult Create()
        {
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title");
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title");

            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "ArticleId,Title,Content,Thumbnail,CreatedDate,ViewsCount,CommentsCount,SeoAuthor,SeoDescription,SeoTags")] Articles articles, HttpPostedFileBase Thumbnail)
        {
            if (ModelState.IsValid)
            {
                
                articles.CreatedDate = DateTime.Now;
                articles.Slug = Kullanici.GetFriendlyTitle(articles.Title);
                articles.ViewsCount = 1;
                articles.CommentsCount = 0;
                articles.UpdateDate = DateTime.Now;
                if (articles.Thumbnail != null)
                {
                    string fileName = articles.Slug + Path.GetExtension(Kullanici.GetFriendlyTitle(Thumbnail.FileName));
                    try
                    {
                        string path = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                        Thumbnail.SaveAs(path);
                        articles.Thumbnail = fileName;
                    }
                    catch (Exception)
                    {
                        articles.Thumbnail = "resim-yok.jpg";
                    }
                }
                db.Articles.Add(articles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            return View(articles);
        }

        // GET: Articles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            return View(articles);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "ArticleId,Title,Content,Thumbnail,CreatedDate,ViewsCount,CommentsCount,SeoAuthor,SeoDescription,SeoTags,Slug")] Articles articles, HttpPostedFileBase Thumbnail)
        {
            if (ModelState.IsValid)
            {
                if(Thumbnail != null)
                {
                    string fileName = articles.Slug + Path.GetExtension(Thumbnail.FileName);
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                    Thumbnail.SaveAs(path);
                    articles.Thumbnail = fileName;
                }
                articles.UpdateDate = DateTime.Now;
                db.Entry(articles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            ViewBag.ArticleId = new SelectList(db.Articles, "ArticleId", "Title", articles.ArticleId);
            return View(articles);
        }
        
        // GET: Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Articles articles = db.Articles.Find(id);
            if (articles == null)
            {
                return HttpNotFound();
            }
            return View(articles);
        }

        // POST: Articles/Delete/5
        [HttpPost]
        public JsonResult Delete(int id)
        {
            try
            {
                Articles articles = db.Articles.Find(id);
                db.Articles.Remove(articles);
                
                db.SaveChanges();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IcMimarlikProje/Areas/admin/Views/Shared/AdminLayout.cshtml
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Sayfası</title>
    <link type="text/css" href="~/AdminSayfaTema/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link type="text/css" href="~/AdminSayfaTema/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <link type="text/css" href="~/AdminSayfaTema/css/theme.css" rel="stylesheet">
    <link type="text/css" href="~/AdminSayfaTema/images/icons/css/font-awesome.css" rel="stylesheet">
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Sayfası</title>

    <script src="/assets/ckeditor/ckeditor.js"></script>
    <script src="/assets/ckeditor/js/sample.js"></script>
    <link href="/assets/ckeditor/css/samples.css" rel="stylesheet" />
    <link href="/assets/ckeditor/toolbarconfigurator/lib/codemirror/neo.css" rel="stylesheet" />
</head>

<html lang="en">

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i>
                </a>


            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->



    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <div class="sidebar">
                        <ul class="widget widget-menu unstyled">

                            <li>
                                <a href="@Url.Action("Index","Articles")"><i class="menu-icon icon-bullhorn"></i>Blog Paneli</a>
                            </li>
                            <li>
                                <a href="message.html">
                                    <i class="menu-icon icon-inbox"></i>Inbox <b class="label green pull-right">

                                    </b>
                                </a>
                            </li>
                            <li>
                                <a href="task.html">
                                    <i class="menu-icon icon-tasks"></i>Tasks <b class="label orange pull-right">

                                    </b>
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Logout","Admin")">
                                    <i class="menu-icon icon-signout"></i>
                                    Logout
                                </a>
                            </li>
                        </ul>

                    </div><!--/.sidebar-->
                </div><!--/.span3-->
                <div class="span9">
                    <div class="content">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div><!--/.container-->
    </div><!--/.wrapper-->

    <script src="/AdminSayfaTema/scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
    <script src="/AdminSayfaTema/scripts/jquery-ui-1.10.1.custom.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="/AdminSayfaTema/bootstrap/js/bootstrap.min.js"></script>
    <script src="/AdminSayfaTema/scripts/datatables/jquery.dataTables.js"></script>
    <script src="//unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", false);
</body>
</html>